exports.register = "insert into user (userId, password, nickName, point) values (?, ?, ?, ?);"
exports.searchUserid = "select userId from user where userId = ?;"
exports.matchPassword = "select userId from user where userId = ? AND password = ?;"
exports.searchNickname = "select nickName from user where nickName = ?;"
exports.getUserbyUserid = "select userId, nickName, isOnline, isAttend from user where userId = ?;"
exports.getUserbyNickname = "select userId, nickName, isOnline, isAttend from user where nickName = ?;"
exports.getNickname = "select nickName from `user` where userId = ?;"

exports.searchUname = "select nickName from user where nickName = ?"
exports.addFriend = "insert into friend (userId, targetId) values (, ?)"
exports.blockFriend = "insert into blocks values (?, ?)"
exports.deleteFriend = "delete from friend where userId = ? and targetId = ?"
exports.listFriend = "select user.userId, nickName, isOnline, isAttend from user left outer join friend on user.userId = friend.targetid where friend.userId = ?"
exports.setOnline = "update `user` set isOnline = true where userId = ?"
exports.setOffline = "update `user` set isOnline = false where userId = ?"

exports.newGroup = "insert into `group` values(?, ?, ?, ?)"
exports.editGroup = "update `group` set group_name = ? , explanation = ?, number_of_people = ?, color = ? where gid = ?"
exports.inviteGroup = "insert into group_participation values (?, ?, ?, ?);"
exports.inviteGroupAccept = "update `group_participation` set is_Accepted = ? where userId = ? AND gid = ?"
exports.kickGroup = "delete from group_participation where gid = ? and userId = ?;"
exports.deleteGroup = "delete from `group`,group_participation,group_plan_belongs where gid=?;"
exports.listGroup = "select group_name from `group` left outer join group_participation on `group`.gid = group_participation.gid where group_participation.userId=?;"
exports.detailsGroup = "select group_name, color, number_of_people, explanation from `group`where gid=?;"

exports.getPopularity = ""
exports.setMyLocation = "update plan_participation set user_latitue=?, user_hardness=? where userId=?;"
exports.getLocation = "select name, user_latitue, user_hardness from user join plan_participation on plan_participation.userId = user.userId where plan_participation.userId=? and pid=?;"

exports.newMemo = "insert into plan_participation(userId, pid, memo) values(?,?,?);"
exports.deleteMemo = "delete from plan_participation where userId=? and pid=?;"
exports.listMemo = "select memo from plan_participation where pid=?;"

exports.newPlan = "insert into plan (name, startTime, endTime, location, category) values(?, str_to_date(?, '%Y-%m-%d %H:%i:%s'), str_to_date(?, '%Y-%m-%d %H:%i:%s'), ?, ?);" +
    "insert into plan_participation(pid, userId) values((select pid from plan where name=? and startTime= str_to_date(?, '%Y-%m-%d %H:%i:%s') and endTime=str_to_date(?, '%Y-%m-%d %H:%i:%s') and location=?), ?);"
exports.editPlan = "update `plan` set name=?, startTime=str_to_date(?, '%Y-%m-%d %H:%i:%s'), endTime=str_to_date(?, '%Y-%m-%d %H:%i:%s'), location=?, category=? where pid = ?;"
exports.invitePlan = "insert into plan_participation(pid, userId, isAccepted) values(?, ?, ?);"
exports.invitePlanAccept = "update plan_participation set isAccepted = true where userId = ? AND pid = ?"
exports.kickPlan = "delete from plan_participation where pid=? and userId=?"
exports.completePlan = "update plan set isDone=true where pid = ?;"
exports.cancelPlan = "delete from plan_participation where userId=? and pid=?;"
exports.getAuthor = "select userId from plan_participation where plan_privilege=true AND pid=?"
exports.setPlanVisibility = "update plan set isPublic= ? where pid = ?;"
exports.deletePlan = "set sql_safe_updates = 0; delete from plan where pid=?; delete from plan_participation where pid=?; set sql_safe_updates = 1;" 
exports.listCurrentPlan = "select plan.pid, name, date_format(startTime, '%Y-%m-%d %H:%i:%s') as startTime, date_format(endTime, '%Y-%m-%d %H:%i:%s') as endTime, location, category, if(isPublic, 'true', 'false') as isPublic from plan left outer join plan_participation on plan_participation.pid = plan.pid where plan_participation.userId= ? and plan.isDone=false;"
exports.listPrevPlan = "select plan.pid, name, date_format(startTime, '%Y-%m-%d %H:%i:%s') as startTime, date_format(endTime, '%Y-%m-%d %H:%i:%s') as endTime, location, category, if(isPublic, 'true', 'false') as isPublic from plan left outer join plan_participation on plan_participation.pid = plan.pid where plan_participation.userId= ? and plan.isDone=false;"
exports.detailsPlan = "select plan.pid, name, date_format(startTime, '%Y-%m-%d %H:%i:%s') as startTime, date_format(endTime, '%Y-%m-%d %H:%i:%s') as endTime, location, category from plan where pid = ?"
exports.listParticipant = "select user.userId, nickName, if(isOnline, 'true', 'false') as isOnline, if(user.isAttend, 'true', 'false') as isAttend from user left outer join plan_participation on plan_participation.userId=user.userId where plan_participation.pid = ?"

exports.newProfile = "insert into user(name,age,gender,profile_image) values(?,?,?,?,?,?)"
exports.editProfile = "update user set nickName=?,name=?,age=?,gender=?,profile_image=? where userId=?"
exports.setNoticeOption = "update user set on_notice=? where userId=?"
exports.setInviteFriendOption = "update user set on_invite_friend=? where userId=?"
exports.setInvitePlanOption = "update user set on_invite_plan=? where userId=?"
exports.logout = "update user set isOnline=false where userId=?;"
exports.getProfile = "select userId,nickName,age,profile_image,login_method,point,gender from user where userId=?"
exports.getStats = ""

exports.getToken = "select token from user where userId = ?"
exports.setToken = "update user set token = ? where userId = ?"
exports.delToken = "delete from user where userId = ?"