exports.register = "insert into user (userid, password, nickname, point) values (?, ?, ?, ?);"
exports.searchUserid = "select userid from user where userid = ?;"
exports.matchPassword = "select userid from user where userid = ? AND password = ?;"
exports.searchNickname = "select nickname from user where nickname = ?;"
exports.getUser = "select * from user where userid = ?;"
exports.getNickname = "select nickname user where userid = ?;"

exports.searchUname = "select nickname from user where nickname = ?"
exports.addFriend = "insert into friend values (?, ?)"
exports.blockFriend = "insert into blocks values (?, ?)"
exports.deleteFriend = "delete from friend where userid = ? and targetid = ?"
exports.listFriend = " select user.userid, nickname, isOnline, isAttend from user left outer join friend on user.userid = friend.targetid where friend.userid = ?"

exports.newGroup = "insert into `group` values(?, ?, ?, ?)"
exports.editGroup = "update `group` set group_name = ? , explanation = ?, number_of_people = ?, color = ? where gid = ?"
exports.inviteGroup = "insert into group_participation values (?, ?, ?, ?);"
exports.inviteGroupAccept = "update `group_participation` set is_Accepted = ? where userid = ? AND gid = ?"
exports.kickGroup = "delete from group_participation where gid = ? and userid = ?;"
exports.deleteGroup = "delete from `group`,group_participation,group_plan_belongs where gid=?;"
exports.listGroup = "select group_name from `group` left outer join group_participation on `group`.gid = group_participation.gid where group_participation.userid=?;"
exports.detailsGroup = "select group_name, color, number_of_people, explanation from `group`where gid=?;"

exports.getPopularity = ""
exports.setMyLocation = "update plan_participation set user_latitue=?, user_hardness=? where userid=?;"
exports.getLocation = "select name, user_latitue, user_hardness from user join plan_participation on plan_participation.userid = user.userid where plan_participation.userid=? and pid=?;"

exports.newMemo = "insert into plan_participation(userid, pid, memo) values(?,?,?);"
exports.deleteMemo = "delete from plan_participation where userid=? and pid=?;"
exports.listMemo = "select memo from plan_participation where pid=?;"

exports.newPlan = "insert into plan (name, startTime, endTime, location, category) values(?, str_to_date(?, '%Y-%m-%d %H:%i:%s'), str_to_date(?, '%Y-%m-%d %H:%i:%s'), ?, ?);" +
    "insert into plan_participation(pid, userid) values((select pid from plan where name=? and startTime= str_to_date(?, '%Y-%m-%d %H:%i:%s') and endTime=str_to_date(?, '%Y-%m-%d %H:%i:%s') and location=?), ?);"
exports.editPlan = "update plan set planname=?, date=?, start_time=?,end_time=?,place_name=?,category=?;"
exports.invitePlan = "insert into plan_participation(pid, userid, is_accepted) values(?, ?, ?);"
exports.invitePlanAccept = "update plan set is_accepted = ? where userid = ? AND pid = ?"
exports.kickPlan = "delete from plan_participation where pid=? and userid=?"
exports.completePlan = "update plan set is_done=1 where pid=?;"
exports.cancelPlan = "delete from plan_participation where userid=? and pid=?;"
exports.setPlanVisibility = "update plan_participation set isPublic=? where pid=?;"
exports.deletePlan = "delete from plan where pid=?;"
exports.listCurrentPlan = "select plan.pid, name, date_format(startTime, '%Y-%m-%d %H:%i:%s') as startTime, date_format(endTime, '%Y-%m-%d %H:%i:%s') as endTime, location, category from plan left outer join plan_participation on plan_participation.pid = plan.pid where plan_participation.userid= ? and plan.isDone=false;"
exports.listPrevPlan = "select plan.pid, name, date_format(startTime, '%Y-%m-%d %H:%i:%s') as startTime, date_format(endTime, '%Y-%m-%d %H:%i:%s') as endTime, location, category from plan left outer join plan_participation on plan_participation.pid = plan.pid where plan_participation.userid= ? and plan.isDone=false;"
exports.detailsPlan = "select * from plan where pid = ?"
exports.listParticipant = "select user.userid, nickname, isOnline, user.isAttend from user left outer join plan_participation on plan_participation.userid=user.userid where plan_participation.pid = ?"

exports.newProfile = "insert into user(name,age,gender,profile_image) values(?,?,?,?,?,?)"
exports.editProfile = "update user set nickname=?,name=?,age=?,gender=?,profile_image=? where userid=?"
exports.setNoticeOption = "update user set on_notice=? where userid=?"
exports.setInviteFriendOption = "update user set on_invite_friend=? where userid=?"
exports.setInvitePlanOption = "update user set on_invite_plan=? where userid=?"
exports.logout = "update user set isOnline=false where userid=?;"
exports.getProfile = "select userid,nickname,age,profile_image,login_method,point,gender from user where userid=?"
exports.getStats = ""

exports.getToken = "select token from user where userid = ?"
exports.setToken = "update user set token = ? where userid = ?"